fos_user:
  db_driver: orm # other valid values are 'mongodb' and 'couchdb'
  firewall_name: main
  user_class: AppBundle\Entity\User
  from_email:
    address: furgaylov5@gmail.com
    sender_name: alex
  registration:
    confirmation:
      template: '@FOSUser/Registration/email.txt.twig'
      from_email:
        address: alexfuraog@gmail.com
        sender_name: demo register