fos_user:
  db_driver: orm
  firewall_name: main
  user_class: Entity\User
  from_email:
    address: "furgaylov5@gmail.com"
    sender_name: "Alex"

  registration:
    confirmation:
      enabled: true
      template:   '@FOSUser/Registration/email.txt.twig'

#  resseting:
#    email:
#      from_email:
#