swiftmailer:
#    transport: "%mailer_transport%"
#    host:      "%mailer_host%"
    username:  alexfuraog@gmail.com
    password:  Boxxx12345
    spool:     { type: memory }
    transport: gmail
    